version: '3'

services:
  web-link-extractor:
    build:
      context: .  # 현재 디렉토리(src)를 빌드 컨텍스트로 사용
    volumes:
      - ./data:/app/data
    # 아래 커맨드를 원하는 인자로 수정하세요
    # command: --url https://example.com --output /app/data/links.csv
